# Site settings
title: Brian  
email: bienpx224@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site

twitter_username:
github_username: bienpx224

# Build settings
markdown: kramdown
